---
title: "Untitled"
author: "Jonas Großekathöfer"
date: "18 7 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("../02_scripts/01-libraries.R")
source("../02_scripts/02-paths.R")
source(path(path_scripts_data, "eyetracking.R"))
source(path(path_scripts_data, "memory.R"))
source(path(path_scripts_data, "questionnaire.R"))
source(path(path_scripts_publ, "dscr_ja.R"))   # joint attention

```


```{r Descriptives}

source(path(path_scripts_publ, "dscr_ja.R"))   # joint attention
source(path(path_scripts_publ, "dscr_sac.R"))  # saccades
source(path(path_scripts_publ, "dscr_mem.R"))  # memory
source(path(path_scripts_publ, "dscr_sa.R"))   # social attention

```

## Gaze following
<!-- #### Fixation latency -->

# nice formatting of results
```{r GLMM memory, warning = TRUE, message = TRUE}

source(path(path_scripts_publ, "glmm_mem.R"))

apa_glmm_mem_mgroup <- "TODO"

apa_glmm_mem_mdur <- "TODO"

apa_glmm_mem_mcnt <- "TODO"

```


```{r, results="asis"}


```

```{r, results="asis"}

apa_table(
    tbl_glmm_results
    , caption = "My table caption"
    , note = "This is the note."
    , landscape = F
    , align = c("l", rep("c", 8)))


```

```{r, results="asis"}

apa_table(
    tbl_glmm_results
    , caption = "My table caption"
    , note = "This is the note."
    , landscape = F
    , align = c("l", rep("l", 8)))


```
